### ISSUE TITLE
Code disagrees with copy in infrastructure-pelican

### ISSUE THREAD

**Issue by sebbASF** [apache/template-site#6]
https://github.com/apache/template-site/blob/a1cd96c48a0d2c8c5299ff884ecb52e39c93ecd8/theme/plugins/asfreader.py#L35

**Comment by dave2wave** [comment]
@gstein made intentional improvements to the gfm.py included in infrastructure-pelican which means that asfreader.py could take a better approach to subclassing `GFMReader`. These will not be backported to the older asfreader.py which will be passed out.

To me the more difficult concern is the older pelican-gfm name when running with infrastructure-pelican buildsite.py is not found.
